SELECT
	COLUMN_NAME + 
	' ' +
	UPPER(DATA_TYPE) +
	CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL THEN '(' + CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) + ')' ELSE '' END +
	CASE WHEN DATETIME_PRECISION IS NOT NULL AND DATETIME_PRECISION > 0 THEN '(' + CAST(DATETIME_PRECISION AS VARCHAR) + ')' ELSE '' END + 
	' ' +
	CASE WHEN IS_NULLABLE = 'YES' THEN  'NULL' ELSE 'NOT NULL' END + --Is NULLable
	',' 
	AS [Statement]
	,*
FROM 
	INFORMATION_SCHEMA.COLUMNS
WHERE 
	TABLE_NAME = ''
	AND TABLE_SCHEMA = ''
ORDER BY 
	ORDINAL_POSITION;
